### ISSUE TITLE
health region box and blue pin

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#85] opened 2020-09-15 11:46 UTC
1) The first time you click on the blue pin, it doesn't change the orientation of the box. You have to click in a second time and then it works. Please make it so the first time you click on the blue pin or **on** the box (like it was before) it changes the orientation.

2) if you move a pin, change its orientation and then drag it somewhere else, it automatically changes it back to its original orientation.

**Comment by Jrschellenberg** [comment] 2020-09-15 14:49
Since this wasn't part of the original scope. And due to time constraints of adding a new feature, I will do this after the AGM

**Comment by DaxBourcier** [comment] 2020-09-15 14:51
But this was working fine before in was moved to the CFMs website that's all.

**Comment by DaxBourcier** [comment] 2020-09-15 14:52
Maybe not the clicking on the box though, but definitely moving the boxes around, they would stay in the orientation you had them in.

**Comment by Jrschellenberg** [comment] 2020-09-15 14:53
Would you like me to remove the functionality of switching orientations? This happened because you asked me to add the x to close the boxes, and as a result, requires 2 clicks to move the box orientation, 1 click to open it if it is closed.

I can try to take a look at it. But as we are getting close to launch I only want to stick to critical bugs

**Comment by DaxBourcier** [comment] 2020-09-15 14:57
Issue 1. is ok as is, I understand now and this is minor.

For issue 2 though, would this be hard to fix? Like I said I'm almost positive this wasn't like this before we moved things over.

**Comment by Jrschellenberg** [comment] 2020-09-15 15:11
@DaxBourcier I see what you mean for number 2. This is in fact a new bug.

This is because of all the changes we have been making in the past week, we are starting to cause regressions in the codebase. This is part of why I'm going to push back on number 1.


But I will fix number 2!

**Comment by DaxBourcier** [comment] 2020-09-15 20:44
Great sounds good, thanks Justin!

**Comment by Jrschellenberg** [comment] 2020-09-15 23:07
Hey there @DaxBourcier 

Good news, I was able to fix both of them.  The first issue wasn't as bad as I thought it would be.
Sorry for pushing back, but just as we are getting closer to the launch date. I am becoming warier of changing lots of lines, which I thought this issue initially would be. The reason for that is, changing more lines, runs the risk of introducing new bugs as well!

Hope you can understand my side of things, and where I am coming from. As I want to make sure the App is rid of critical bugs and Functional for the launch!

Closing this Ticket for now, if you find any other issues and want to reopen it just let me know!

**Closed as completed by Jrschellenberg** 2020-09-15 23:07 UTC
Labels: bug

**Comment by DaxBourcier** [comment] 2020-09-15 23:08
Oh 100%!! Thanks Justin!
